name: Terraform Destroy

on:
  workflow_dispatch:   # 🔥 manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: prod   # 🔒 approval required

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
